### PR TITLE
Change symbology

### LINKED ISSUE #21: Maud and macro_rules don't play well together
This doesn't work:

```rust
macro_rules! greet {
    () => ({
        let mut result = String::new();
        let name = "Pinkie Pie";
        html!(result, p { "Hello, " $name "!" });
        result
    })
}
```

That's because `macro_rules!` tries to expand `$name` itself, when it should be handled by Maud instead.

We can probably work around that by adding a new `#splice` magic operator. So the code above would look like this:

```rust
// ...
html!(result, p { "Hello, " #splice name "!" });
// ...
```

This works because it doesn't have a `$` in it.

See rust-lang/rust#6994

### PR DESCRIPTION
**Pull request by Nemo157**
* Change `$` -> `^` and `#` -> `@`.
 * Add in support for render by move (with test showing it will still default to by-ref if needed).
 * Add in some more tests.
 * Remove symbol from `#else` (I guess this could break using an element called `else`, but who's gonna do that?)

Fixes #21, #24 and #26.

### CODE REVIEW

File: maud_macros/tests/tests.rs [hunk 1]
```diff
@@ -327,6 +327,100 @@ fn splice_with_path() {
...
+        fn render(&self, w: &mut std::fmt::Write) -> std::fmt::Result {
+            w.write_str(self.0)
+        }
+    }
+
+    let mut s = String::new();
+    let r = R("pinkie ");
+    html!(s, ^r).unwrap();
+    html!(s, ^r).unwrap();
+    // R is not-Copyable so this shows that it will auto-ref splice arguments that implement Render.
```
Comment (Nemo157) [inline maud_macros/tests/tests.rs]: Here's the test showing that the compiler auto-refs the spliced values.

**Comment by lfairy** [comment]
:+1: for using trait auto-ref.

I'll have to disagree on removing the sigil from `else`. Though I admit it looks cleaner, as with the shorthand class syntax it makes the grammar ambiguous, and precludes us from adding XML support in the future. That's not worth removing one character over IMO.

The rest of the patch looks good, so I'll be happy to merge once this is addressed.

**Comment by Nemo157** [comment]
Ah, yep, I did wonder why it would be needed, but XML support makes sense. I'll add it back.
